#!/usr/bin/sh
# @author nate zhou
# @since 2025
# file opener for lf

cmd open &{{
    case $(file --mime-type -Lb $f) in
        image/x-xcf)
            gimp $fx
            ;;
        image/*)
            [ "$XDG_SESSION_TYPE" = "tty" ] && mpv --loop $fx || swayimg $fx
            ;;
        video/*|audio/*)
            mpv --loop $fx
            ;;
        application/zip)
            lf -remote "send $id \$zipinfo \$f | less -i"
            ;;
        application/*tar|application/*zip*|application/zstd|application/*xz)
            lf -remote "send $id \$tar vvtf \$f | less -i"
            ;;
        */pdf|*/epub)
            zathura $fx
            ;;
		doc|docx|xls|xlsx|odt|ppt|pptx)
            libreoffice $fx
            ;;
        text/html)
            firejail firefox $fx
            ;;
        text/*|*/json)
            lf -remote "send $id \$$EDITOR \$fx"
            ;;
        #*)
        #    for f in $fx; do $OPENER $f > /dev/null 2> /dev/null & done
        #    ;;
    esac
}}
