#!/usr/bin/sh
# @author nate zhou
# @since 2025
# river/autostart

# always
riverctl spawn "$HOME/.local/bin/wlr-output"
riverctl spawn "${HOME}/.local/bin/dam-run"

# restart
killall -q swaybg fcitx5 mpc

riverctl spawn "swaybg -i $HOME/.local/share/wallpaper -m fill"

# restart decided by scripts
riverctl spawn "$HOME/.local/bin/foots"

riverctl spawn "$HOME/.local/sbin/clsd"

# start if not running
pgrep 'swayidle' || riverctl spawn "swayidle"

pgrep "gammastep" || riverctl spawn "gammastep -O 5000"

pgrep -f 'wl-paste --watch cliphist store' || riverctl spawn "wl-paste --watch cliphist store"

pgrep 'dunst' || riverctl spawn "dunst"

pgrep 'wob' || riverctl spawn "$HOME/.local/bin/wobd"

pgrep 'mbs-cron' || riverctl spawn "$HOME/.local/bin/mbs-cron"

riverctl spawn "fcitx5 -d" # conflicts with wtype

#pgrep -f 'footclient -T Scratchpad_Tmux' || riverctl spawn "footclient -T Scratchpad_Tmux $HOME/.local/bin/tmuxd" # disabled for not obeying window rules, start manually instead
