#!/usr/bin/sh
# @author nate zhou
# @since 2025
# river/autostart

# restart
killall -q  swaybg

riverctl spawn "swaybg -i $HOME/.local/share/wallpaper -m fill"

# restart decided by scripts
riverctl spawn "$HOME/.local/bin/foots" # foot server

riverctl spawn "$HOME/.local/sbin/clsd"

# start if not running
pgrep 'i3bar-river' || riverctl spawn "i3bar-river"

pgrep 'swayidle' || riverctl spawn "swayidle -w timeout 600 'brightnessctl set 4% -s' resume 'brightnessctl -r' timeout 900 'swaylock'"

pgrep "gammastep">/dev/null || riverctl spawn "gammastep -O 5000"

pgrep -f 'wl-paste --watch cliphist store' || riverctl spawn "wl-paste --watch cliphist store"

pgrep -f 'fcitx5 -d'>/dev/null || riverctl spawn "fcitx5 -d"

pgrep 'dunst' || riverctl spawn "dunst"

pgrep 'wob'>/dev/null || riverctl spawn "$HOME/.local/bin/wobd" # wob daemon
