#!/usr/bin/sh
# @author nate zhou
# @since 2025
# river/init

. $HOME/.local/bin/colors.sh    # source colorscheme
. $HOME/.config/river/bindings
. $HOME/.config/river/autostart

# window manager
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &

# remap key
riverctl keyboard-layout-file "$HOME/.config/river/layout.xkb"

# output
riverctl spawn "wlr-randr --output eDP-1 --custom-mode 1920x1080@60.000Hz --pos 0,0 --output DP-1 --custom-mode 1920x1080@60.000Hz --pos -1920,0"

# input
riverctl set-repeat 30 200

# color
riverctl border-color-focused 0xb16286
riverctl border-color-unfocused 0x586e75

# server side decorations(ssd)
riverctl rule-add -app-id firefox ssd   # fix border
