#!/usr/bin/sh
# @author nate zhou
# @since 2025
# river/init

. $HOME/.local/bin/colors.sh    # source colorscheme
. $HOME/.config/river/autostart
. $HOME/.config/river/bindings
. $HOME/.config/river/modes

# remap key
riverctl keyboard-layout-file "$HOME/.config/layout.xkb"

# output
riverctl spawn "$HOME/.local/bin/wlr-output"

# layout
. $HOME/.config/river/rivercarro
#. $HOME/.config/river/rivertile

# input
riverctl set-repeat 30 200

riverctl hide-cursor timeout 3000
riverctl hide-cursor when-typing enabled

for i in $(riverctl list-inputs | grep -i touchpad); do
    riverctl input "$i" tap enabled
done

# border
riverctl border-color-focused 0xb16286
riverctl border-color-unfocused 0x586e75
riverctl border-width 3

# window rules
riverctl rule-add -app-id "*" ssd   # fix border for every window
riverctl rule-add -app-id "file-*" float # GIMP file import/export
riverctl rule-add -app-id "script-fu" float # GIMP gegl operations

# tags
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))
    riverctl map normal $mod $i set-focused-tags $tags
    riverctl map normal ${mod}+Shift $i set-view-tags $tags
    riverctl map normal Control $i toggle-focused-tags $tags
    riverctl map normal ${mod}+Control $i toggle-view-tags $tags
done
# tag 10
riverctl map normal $mod 0 set-focused-tags $((1 << (10 - 1)))
riverctl map normal ${mod}+Shift 0 set-view-tags $((1 << (10 - 1)))
riverctl map normal Control 0 toggle-focused-tags $((1 << (10 - 1)))
riverctl map normal ${mod}+Control 0 toggle-view-tags $((1 << (10 - 1)))

# scratchpad
# The scratchpad will live on an unused tag. Which tags are used depends on your
# config, but rivers default uses the first 9 tags.
scratch_tag=$((1 << 20 ))

# Toggle the scratchpad
riverctl map normal $mod s toggle-focused-tags ${scratch_tag}

# Send windows to the scratchpad
riverctl map normal ${mod}+Shift s set-view-tags ${scratch_tag}

# Scratchpad_Tmux rules
riverctl rule-add -app-id footclient -title Scratchpad_Tmux tags ${scratch_tag}
riverctl rule-add -app-id footclient -title Scratchpad_Tmux float

# Set spawn tagmask to ensure new windows don't have the scratchpad tag unless
# explicitly set.
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ $scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}
