#!/usr/bin/sh
# @author nate zhou
# @since 2025
# river/init

. $HOME/.local/bin/colors.sh    # source colorscheme
. $HOME/.config/river/bindings
. $HOME/.config/river/autostart
. $HOME/.config/river/modes

# window manager
riverctl default-layout rivercarro
rivercarro -per-tag -no-smart-gaps -inner-gaps 5 -outer-gaps 5 -main-ratio 0.50 &

# remap key
riverctl keyboard-layout-file "$HOME/.config/layout.xkb"

# output
riverctl spawn "$HOME/.local/bin/wlr-output"

riverctl focus-output left
riverctl send-layout-cmd rivercarro "main-location left"

riverctl focus-output right
riverctl send-layout-cmd rivercarro "main-location left"

# input
riverctl set-repeat 30 200

riverctl hide-cursor timeout 3000
riverctl hide-cursor when-typing enabled

for i in $(riverctl list-inputs | grep -i touchpad); do
    riverctl input "$i" tap enabled
done

# border
riverctl border-color-focused 0xb16286
riverctl border-color-unfocused 0x586e75
riverctl border-width 3

# window rules
riverctl rule-add -app-id "*" ssd   # fix border for every window
riverctl rule-add -app-id "file-*" -title "Export Image as *" float # GIMP
riverctl rule-add -app-id "script-fu" float # GIMP gegl operations

# tags
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))
    riverctl map normal $mod $i set-focused-tags $tags
    riverctl map normal ${mod}+Shift $i set-view-tags $tags
    riverctl map normal Control $i toggle-focused-tags $tags
    riverctl map normal ${mod}+Control $i toggle-view-tags $tags
done
# tag 10
riverctl map normal $mod 0 set-focused-tags $((1 << (10 - 1)))
riverctl map normal ${mod}+Shift 0 set-view-tags $((1 << (10 - 1)))
riverctl map normal Control 0 toggle-focused-tags $((1 << (10 - 1)))
riverctl map normal ${mod}+Control 0 toggle-view-tags $((1 << (10 - 1)))
