#!/usr/bin/sh
# river/modes
# @author nate zhou
# @since 2025

mod=Mod4
mode_fcitx="[p]inyin [a]nthy"
mode_wmenu="[w[w]iki w[h]eart w[b]ook [a]mount [f]locks [p]off w[m]ulti w[s]ink w[j]doc"

riverctl declare-mode "$mode_fcitx"
riverctl map normal ${mod}+Shift space enter-mode "$mode_fcitx"
riverctl map "$mode_fcitx" ${mod}+Shift space enter-mode normal
riverctl map "$mode_fcitx" None Escape enter-mode normal
riverctl map "$mode_fcitx" None space enter-mode normal
riverctl map "$mode_fcitx" None p spawn "fcitx5-remote -s pinyin && riverctl enter-mode normal"
riverctl map "$mode_fcitx" None a spawn "fcitx5-remote -s anthy && riverctl enter-mode normal"


riverctl declare-mode "$mode_wmenu"
riverctl map normal $mod w enter-mode "$mode_wmenu"
riverctl map "$mode_wmenu" $mod w enter-mode normal
riverctl map "$mode_wmenu" None space enter-mode normal
riverctl map "$mode_wmenu" None Escape enter-mode normal
riverctl map "$mode_wmenu" None w spawn "riverctl enter-mode normal && $HOME/.local/bin/wwiki"
riverctl map "$mode_wmenu" None h spawn "riverctl enter-mode normal && $HOME/.local/bin/wheart"
riverctl map "$mode_wmenu" None b spawn "riverctl enter-mode normal && $HOME/.local/bin/wbook"
riverctl map "$mode_wmenu" None a spawn "riverctl enter-mode normal && $HOME/.local/bin/amount"
riverctl map "$mode_wmenu" None f spawn "riverctl enter-mode normal && $HOME/.local/bin/flocks"
riverctl map "$mode_wmenu" None p spawn "riverctl enter-mode normal && $HOME/.local/bin/poff"
riverctl map "$mode_wmenu" None m spawn "riverctl enter-mode normal && $HOME/.local/bin/wmulti"
riverctl map "$mode_wmenu" None s spawn "riverctl enter-mode normal && $HOME/.local/bin/wsink"
riverctl map "$mode_wmenu" None j spawn "riverctl enter-mode normal && $HOME/.local/bin/wjdoc"
